"""Migrating books, companies, users

Revision ID: 08e0d1c99775
Revises: 
Create Date: 2026-05-02 15:00:59.969754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e0d1c99775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('contact', sa.String(length=50), nullable=False),
                    sa.Column('image', sa.String(length=255), nullable=True),
                    sa.Column('password', sa.Text(), nullable=False),
                    sa.Column('biography', sa.Text(), nullable=True),
                    sa.Column('user_type', sa.String(
                        length=20), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('contact'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('company',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('origin', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('book',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=150), nullable=False),
                    sa.Column('pages', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('price_unit', sa.String(
                        length=50), nullable=False),
                    sa.Column('publication_date', sa.Date(), nullable=False),
                    sa.Column('isbn', sa.String(length=30), nullable=True),
                    sa.Column('genre', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=False),
                    sa.Column('image', sa.String(length=255), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('company_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('isbn')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('company')
    op.drop_table('users')
    # ### end Alembic commands ###
